### PR TITLE
Fix recipe

### PR DESCRIPTION
**Pull request by marcelotrevisani**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
@conda-forge/help-go

**Comment by marcelotrevisani** [comment]
cc: @mariusvniekerk @sodre 
Could you please take a look on this recipe?
``go`` is not my cup of tea
:smile:

**Comment by ocefpaf** [comment]
Pinging @sodre and @mariusvniekerk for help with go here.

**Comment by andrew-mcgrath** [comment]
@marcelotrevisani I've fixed the linux and OSX builds but windows is failing at the conda build bootstrap phase.

**Comment by andrew-mcgrath** [comment]
@marcelotrevisani I'm closing this PR due to the issue being resolved with version 0.8.2 now existing for each OS published.  Thanks for being on top of things and noticing it hadn't built properly.

**Pull request closed without merging**
